# Nombre de la app
spring.application.name=TechnoExpress - IT eCommerce

# Configuracion de base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/techno_express?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# Configuracion de logs
logging.level.root=DEBUG
logging.level.techno_express.backend=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

# Configuracion general para debugear por si rompe algo
server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true

# Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false